services:
  web:
    image: "${DOCKER_REPO:-beaver-iot}/web"
    build:
      context: .
      dockerfile: ./web.dockerfile
      target: web
      network: host
      args:
        - "WEB_GIT_REPO_URL=${WEB_GIT_REPO_URL:-}"
        - "WEB_GIT_BRANCH=${WEB_GIT_BRANCH:-origin/develop}"
      tags:
        - "${DOCKER_REPO:-beaver-iot}/web:${PRODUCTION_TAG:-latest}"
  server:
    image: "${DOCKER_REPO:-beaver-iot}/server"
    build:
      context: .
      dockerfile: ./server.dockerfile
      target: server
      network: host
      args:
        - "SERVER_GIT_REPO_URL=${SERVER_GIT_REPO_URL:-}"
        - "SERVER_GIT_BRANCH=${SERVER_GIT_BRANCH:-origin/dev}"
      tags:
        - "${DOCKER_REPO:-beaver-iot}/server:${PRODUCTION_TAG:-latest}"
  monolith:
    image: "${DOCKER_REPO:-beaver-iot}/monolith"
    depends_on:
      - web
      - server
    build:
      context: .
      dockerfile: ./monolith.dockerfile
      target: monolith
      network: host
      args:
        - "SERVER_GIT_REPO_URL=${SERVER_GIT_REPO_URL:-}"
        - "SERVER_GIT_BRANCH=${SERVER_GIT_BRANCH:-origin/dev}"
        - "WEB_GIT_REPO_URL=${WEB_GIT_REPO_URL:-}"
        - "WEB_GIT_BRANCH=${WEB_GIT_BRANCH:-origin/develop}"
        - "BASE_SERVER_IMAGE=${DOCKER_REPO:-beaver-iot}/server:${PRODUCTION_TAG:-latest}"
        - "BASE_WEB_IMAGE=${DOCKER_REPO:-beaver-iot}/web:${PRODUCTION_TAG:-latest}"
      tags:
        - "${DOCKER_REPO:-beaver-iot}/monolith:${PRODUCTION_TAG:-latest}"
